### ISSUE TITLE
Difference between this and normalize.css?

### ISSUE THREAD

**Issue by blueridgemountains1** [zlatanvasovic/codify.css#7]
What benefits does this package offer over normalize? Thanks!

**Comment by ZDroid** [comment]
From README:

> ## Core changes
> (compared to Normalize.css)
>
> * Modules
> * CSSComb support
> * Improved display definitions
> * Consistent element styles
> * Improved vertical align of embedded content
> * Responsive images

At the moment I am a bit busy in RL. Hopefully I'll continue managing it soon. ^^

**Comment by ZDroid** [comment]
:fireworks:
